import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#d8b9ff",
        "secondary-container": "#00ec91",
        "inverse-surface": "#e0e3e6",
        "surface-dim": "#101416",
        surface: "#101416",
        "on-tertiary-fixed-variant": "#45474b",
        "on-secondary-fixed-variant": "#00522f",
        "on-tertiary": "#2e3035",
        "inverse-primary": "#7f21e5",
        "outline-variant": "#4c4355",
        "on-surface": "#e0e3e6",
        "on-secondary": "#00391f",
        "on-background": "#e0e3e6",
        "tertiary-fixed-dim": "#c6c6cb",
        "on-primary": "#450086",
        "secondary-fixed": "#56ffa8",
        tertiary: "#c6c6cb",
        "surface-bright": "#363a3c",
        "primary-container": "#9945ff",
        "surface-container-high": "#272a2d",
        "on-surface-variant": "#cec2d8",
        "surface-container-lowest": "#0b0f11",
        "on-secondary-fixed": "#002110",
        "surface-container": "#1d2022",
        error: "#ffb4ab",
        "inverse-on-surface": "#2d3133",
        "tertiary-container": "#75767b",
        "on-error": "#690005",
        "on-tertiary-container": "#ffffff",
        "surface-container-highest": "#323538",
        outline: "#978da1",
        "on-error-container": "#ffdad6",
        background: "#101416",
        "tertiary-fixed": "#e2e2e8",
        secondary: "#a0ffc3",
        "primary-fixed-dim": "#d8b9ff",
        "primary-fixed": "#eddcff",
        "on-secondary-container": "#00653b",
        "on-tertiary-fixed": "#1a1c20",
        "error-container": "#93000a",
        "surface-variant": "#323538",
        "surface-tint": "#d8b9ff",
        "on-primary-fixed": "#290055",
        "on-primary-container": "#ffffff",
        "secondary-fixed-dim": "#00e38b",
        "surface-container-low": "#191c1e",
        "on-primary-fixed-variant": "#6300bb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "24px",
        "container-padding": "24px",
        base: "8px",
        "stack-lg": "48px",
        gutter: "16px",
        "stack-sm": "12px",
      },
      fontFamily: {
        "data-mono": ["Inter", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "display-xl": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "data-mono": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;